name: MLflow Training Workflow

on: [push]

jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Secrets (Check if they exist)
        env:
          MY_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MY_USER: ${{ secrets.DAGSHUB_USERNAME }}
        run: |
          if [ -z "$MY_TOKEN" ]; then
            echo "FATAL ERROR: DAGSHUB_TOKEN is empty or not found!"
            exit 1
          else
            echo "SUCCESS: DAGSHUB_TOKEN is found (masked)."
          fi

          if [ -z "$MY_USER" ]; then
            echo "FATAL ERROR: DAGSHUB_USERNAME is empty or not found!"
            exit 1
          else
            echo "SUCCESS: DAGSHUB_USERNAME is found: $MY_USER"
          fi

      - name: Run MLflow Project
        env:
          MLFLOW_TRACKING_URI: "https://dagshub.com/galihthecreator/Eksperimen_SML_Galih.mlflow"
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_REPO: "Eksperimen_SML_Galih"
        run: mlflow run . --env-manager=local
